In [1]:
import parse_sched

In [4]:
sched = parse_sched.ical_to_df('schedule.ics')

In [14]:
blah = sched.set_index('start', drop=False).sort_index()

In [90]:
start_dt.timetz()

datetime.time(0, 0)

In [93]:
START_DAY = '2022-05-07 00:00:00 UTC'
END_DAY = '2022-05-09 00:00:00 UTC'
RESIDENTS = ['M Newton', 'J Greco', 'M Spadafore']

start_dt = pd.Timestamp(START_DAY)
end_dt = pd.Timestamp(END_DAY)

blah = sched.copy().set_index('start', drop=False).sort_index()
blah = blah[START_DAY:END_DAY]
blah = blah[blah['resident'].isin(RESIDENTS)]
blah['start_day'] = blah['start'].dt.dayofyear
blah['end_day'] = blah['end'].dt.dayofyear
blah['start_hour'] = blah['start'].dt.hour
blah['end_hour'] = blah['end'].dt.hour

# initial_start = blah.iloc[0,:]['start']
initial_start = start_dt
# td = blah.iloc[-1,:]['end'] - blah.iloc[0,:]['start']
td = end_dt - start_dt
n_hours = td.total_seconds() / (60*60) # indexed by relative hour
hmat = np.zeros((len(RESIDENTS), int(n_hours)), dtype='int')
hdf = pd.DataFrame(hmat, index=RESIDENTS)

for idx, row in blah.iterrows():
    start_hour = (row['start'] - initial_start).total_seconds() / (60*60)
    end_hour = (row['end'] - initial_start).total_seconds() / (60*60)
    hdf.loc[row['resident'], start_hour:end_hour] = 1

hdf

hdf.columns = [initial_start + pd.Timedelta(hours=i) for i in range(hdf.shape[1])]

hdf
# for idx, row in blah.iterrows()

# for i in range(24):
#     blah[i] = 0

# for idx, row in blah.iterrows():
#     print(idx)
#     print(row['start_hour'], row['end_hour'])
#     start_hour = row['start_hour']
#     end_hour = row['end_hour']
#     blah.loc[idx, row['start_hour']:row['end_hour']] = 1

,2022-05-07 00:00:00+00:00,2022-05-07 01:00:00+00:00,2022-05-07 02:00:00+00:00,2022-05-07 03:00:00+00:00,2022-05-07 04:00:00+00:00,2022-05-07 05:00:00+00:00,2022-05-07 06:00:00+00:00,2022-05-07 07:00:00+00:00,2022-05-07 08:00:00+00:00,2022-05-07 09:00:00+00:00,...,2022-05-08 14:00:00+00:00,2022-05-08 15:00:00+00:00,2022-05-08 16:00:00+00:00,2022-05-08 17:00:00+00:00,2022-05-08 18:00:00+00:00,2022-05-08 19:00:00+00:00,2022-05-08 20:00:00+00:00,2022-05-08 21:00:00+00:00,2022-05-08 22:00:00+00:00,2022-05-08 23:00:00+00:00
M Newton,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
J Greco,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
M Spadafore,0,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,1,1,1,1

In [92]:
end_dt

Timestamp('2022-05-09 00:00:00+0000', tz='tzutc()')

In [80]:
initial_start + pd.Timedelta(hours=1)

Timestamp('2022-05-07 20:00:00+0000', tz='tzutc()')

In [49]:
td = blah.iloc[-1,:]['end'] - blah.iloc[0,:]['start']

In [57]:
td.total_seconds() / (60*60)

56.0

In [40]:
blah.loc[:,0:23].sum(axis=1)

start
2022-05-07 19:00:00+00:00     0
2022-05-07 23:00:00+00:00     0
2022-05-08 11:00:00+00:00    13
2022-05-09 15:00:00+00:00     0
dtype: int64

In [58]:
import numpy as np
import pandas as pd

In [34]:
blah.loc[:,0:7]

                           0  1  2  3  4  5  6  7
start
2022-05-07 19:00:00+00:00  0  0  0  0  0  0  0  0
2022-05-07 23:00:00+00:00  0  0  0  0  0  0  0  0
2022-05-08 11:00:00+00:00  0  0  0  0  0  0  0  0
2022-05-09 15:00:00+00:00  0  0  0  0  0  0  0  0

In [26]:
blah[0] = 0

In [27]:
blah

,summary,resident,shift,start,end,type,facility,start_day,end_day,0
start,,,,,,,,,,
2022-05-07 19:00:00+00:00,UM UL J Greco,J Greco,UL,2022-05-07 19:00:00+00:00,2022-05-08 03:00:00+00:00,"EM 4 (UJ, UL, SJ, SL)",University of Michigan,127,128,0
2022-05-07 23:00:00+00:00,UM J PM M Newton,M Newton,Jeopardy PM,2022-05-07 23:00:00+00:00,2022-05-08 11:00:00+00:00,Jeopardy,University of Michigan,127,128,0
2022-05-08 11:00:00+00:00,UM J AM M Spadafore,M Spadafore,Jeopardy AM,2022-05-08 11:00:00+00:00,2022-05-08 23:00:00+00:00,Jeopardy,University of Michigan,128,128,0
2022-05-09 15:00:00+00:00,UM 11a-11p EC3 M Spadafore,M Spadafore,11:00am-11:00pm EC3,2022-05-09 15:00:00+00:00,2022-05-10 03:00:00+00:00,"EM 2,3,4 (EC3 Shifts)",University of Michigan,129,130,0

In [ ]:
blah.groupby(['resident',''])

S[res,hour,day]